require("lspsaga").init_lsp_saga({
	diagnostic_header = { " ", " ", "  ", " " },
	custom_kind = {
		File = { " " },
		Module = { " " },
		Namespace = { " " },
		Package = { " " },
		Class = { "ﴯ " },
		Method = { " " },
		Property = { "ﰠ " },
		Field = { " " },
		Constructor = { " " },
		Enum = { " " },
		Interface = { " " },
		Function = { " " },
		Variable = { " " },
		Constant = { " " },
		String = { " " },
		Number = { " " },
		Boolean = { " " },
		Array = { " " },
		Object = { " " },
		Key = { " " },
		Null = { "ﳠ " },
		EnumMember = { " " },
		Struct = { " " },
		Event = { " " },
		Operator = { " " },
		TypeParameter = { " " },
		-- ccls-specific icons.
		TypeAlias = { " " },
		Parameter = { " " },
		StaticMethod = { "ﴂ " },
		Macro = { " " },
	},
})
