-- require("which-key").register({
--   s = {
--     name = "LspSaga",
--     f = { "<cmd>Lspsaga lsp_finder<CR>", "Finder" },
--     n = { "<cmd>Lspsaga rename<CR>", "Rename" },
--     c = { "<cmd>Lspsaga show_cursor_diagnostics<CR>", "Show Cursor Diagnostics" },
--     k = { "<cmd>Lspsaga hover_doc<CR>", "Hover Doc" },
--     o = { "<cmd>LSoutlineToggle<CR>", "Outline Toggle" },
--   },
-- }, { prefix = "<leader>", silent = true, noremap = true })
