local script = require("core.script")
require("core")
require("modules")
script.req("modules.which_key", "which-key")

script.req("modules.notify", "notify")
script.req("modules.colorscheme", "gruvbox", "rose-pine", "tokyonight", "nightfox")
script.req("modules.bufferline", "bufferline")
script.req("modules.nvim_tree", "nvim-tree")
script.req("modules.treesitter", "nvim-treesitter")
script.req("modules.indentline", "indent_blankline")
script.req("modules.autopairs", "nvim-autopairs")
script.req("modules.comment", "Comment")
script.req("modules.toggleterm", "toggleterm")
script.req("modules.lsp", "lspconfig")
script.req("gitsigns", "gitsigns")
script.req("alpha", "alpha")
script.req("symbols_outline", "packer")
