return vim.schedule_wrap(function()
	vim.api.nvim_set_option_value("foldmethod", "expr", {})
	vim.api.nvim_set_option_value("foldexpr", "nvim_treesitter#foldexpr()", {})

	require("nvim-treesitter").install({
		"bash",
		"c",
		"c_sharp",
		"cpp",
		"css",
		"csv",
		"dockerfile",
		"dot",
		"fsh",
		"go",
		"gomod",
		"gosum",
		"gowork",
		"html",
		"htmldjango",
		"javascript",
		"json",
		"json5",
		"julia",
		"lua",
		"luadoc",
		"luap",
		"luau",
		"markdown",
		"proto",
		"python",
		"query",
		"rust",
		"rust_with_rstml",
		"toml",
		"tsx",
		"typescript",
		"yaml",
	})
end)
