require("nvim-web-devicons").setup({
	override = {
		[".zsh"] = {
			icon = "",
			color = "#ff79c6",
			cterm_color = "65",
			name = "Zsh",
		},
		[".zshenv"] = { icon = "", color = "#ff79c6", name = "Zshenv" },
		[".zprofile"] = { icon = "", color = "#ff79c6", name = "Zshprofile" },
		[".bashrc"] = { icon = "", color = "#ff79c6", name = "Bashrc" },
		[".bash_profile"] = { icon = "", color = "#ff79c6", name = "BashProfile" },
		[".gitconfig"] = { icon = "", color = "#ff79c6", name = "GitConfig" },
		[".gitignore"] = { icon = "", color = "#ff79c6", name = "GitIgnore" },
		[".gitmodules"] = { icon = "", color = "#ff79c6", name = "GitModules" },
		[".gitattributes"] = { icon = "", color = "#ff79c6", name = "GitAttributes" },
		lock = { icon = "", color = "#ff79c6", name = "Lock" },
		fnl = { icon = "", color = "#ff79c6", name = "Fennel" },
		makefile = { icon = "", color = "#ff79c6", name = "Makefile" },
		toml = { icon = "", color = "#ff79c6", name = "Toml" },
		yml = { icon = "", color = "#ff79c6", name = "Yaml" },
		conf = { icon = "", color = "#ff79c6", name = "conf" },
		lua = { icon = "", color = "#ff79c6", name = "Lua" },
		rs = { icon = "", color = "#ff79c6", name = "Rust" },
		nix = { icon = "", color = "#ff79c6", name = "Nix" },
		LICENSE = { icon = "", color = "#ff79c6", name = "License" },
		ps1 = { icon = "", color = "#ff79c6", name = "PromptPs1" },
		sh = { icon = "", color = "#ff79c6", name = "Sh" },
	},
	color_icons = true,
	default = true,
})
