return function()
	require("lspkind").init({
		mode = "symbol_text",
		preset = "codicons",
		symbol_map = {
			Text = "",
			Method = "",
			Function = "",
			Constructor = "",
			Field = "",
			Variable = "",
			Class = "ﴯ",
			Interface = "",
			Module = "",
			Property = "ﰠ",
			Unit = "",
			Value = "",
			Enum = "",
			Keyword = "",
			Snippet = "",
			Color = "",
			File = "",
			Reference = "",
			Folder = "",
			EnumMember = "",
			Constant = "",
			Struct = "",
			Key = "",
			Event = "",
			Operator = "",
			TypeParameter = "",
			Array = "",
			Boolean = "蘒",
			Namespace = "",
			Number = "",
			Null = "ﳠ",
			Object = "",
			-- Package = "",
			Package = "",
			String = "",
		},
	})
end
