require("nvim-treesitter.configs").setup({
  ensure_installed = {
    "bash",
    "c",
    "c_sharp",
    "cmake",
    "comment",
    "cpp",
    "css",
    "cuda",
    "dart",
    "dockerfile",
    "dot",
    "elm",
    "fish",
    "gdscript",
    "go",
    "godot_resource",
    "gomod",
    "gowork",
    "graphql",
    "hack",
    "haskell",
    "html",
    "http",
    "java",
    "javascript",
    "jsdoc",
    "json",
    "json5",
    "jsonc",
    "jsonnet",
    "julia",
    "kotlin",
    "llvm",
    "lua",
    "make",
    "markdown",
    "markdown_inline",
    "meson",
    "ninja",
    "nix",
    "ocaml",
    "ocaml_interface",
    "ocamllex",
    "pascal",
    "perl",
    "php",
    "python",
    "query",
    "r",
    "ruby",
    "rust",
    "sql",
    "surface",
    "swift",
    "toml",
    "tsx",
    "v",
    "vim",
    "vue",
    "wgsl",
    "yang",
    "zig",
  },
  sync_install = false,
  auto_install = true,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  autotag = { enable = true, },
  endwise = { enable = true, },
  rainbow = { enable = true, extended_mode = true },
  matchup = { enable = true, },
  textobjects = {
    select = {
      enable = true,
      keymaps = {
        ["af"] = "@function.outer",
        ["if"] = "@function.inner",
        ["ac"] = "@class.outer",
        ["ic"] = "@class.inner",
      },
    },
    move = {
      enable = true,
      set_jumps = true, -- whether to set jumps in the jumplist
      goto_next_start = {
        ["]["] = "@function.outer",
        ["]m"] = "@class.outer",
      },
      goto_next_end = {
        ["]]"] = "@function.outer",
        ["]M"] = "@class.outer",
      },
      goto_previous_start = {
        ["[["] = "@function.outer",
        ["[m"] = "@class.outer",
      },
      goto_previous_end = {
        ["[]"] = "@function.outer",
        ["[M"] = "@class.outer",
      },
    },
  },
  context_commentstring = { enable = true, enable_autocmd = false },

})
