require("nvim-treesitter.configs").setup({
	ensure_installed = {
    "bash",
    "c",
    "c_sharp",
    "cmake",
    "comment",
    "cpp",
    "css",
    "cuda",
    "dart",
    "dockerfile",
    "dot",
    "elm",
    "fish",
    "gdscript",
    "go",
    "godot_resource",
    "gomod",
    "gowork",
    "graphql",
    "hack",
    "haskell",
    "html",
    "http",
    "java",
    "javascript",
    "jsdoc",
    "json",
    "json5",
    "jsonc",
    "jsonnet",
    "julia",
    "kotlin",
    "llvm",
    "lua",
    "make",
    "markdown",
    "markdown_inline",
    "meson",
    "ninja",
    "nix",
    "ocaml",
    "ocaml_interface",
    "ocamllex",
    "pascal",
    "perl",
    "php",
    "python",
    "query",
    "r",
    "ruby",
    "rust",
    "sql",
    "surface",
    "swift",
    "toml",
    "tsx",
    "v",
    "vim",
    "vue",
    "wgsl",
    "yang",
    "zig",
  },
	sync_install = false,
	auto_install = true,
	highlight = {
		enable = true,
		additional_vim_regex_highlighting = false,
	},
	autotag = { enable = true, },
	endwise = { enable = true, },
	rainbow = { enable = true, extended_mode = true },
	matchup = { enable = true, },
})
